# Generated by Django 2.2.8 on 2019-12-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191015_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'all'), (1, 'web-development'), (2, 'data-structure'), (3, 'android-development'), (4, 'c-programming')], default=0),
        ),
    ]
